"""drop screenshots.source Column

Revision ID: 33b46dbcb03e
Revises: 
Create Date: 2022-09-18 23:21:14.956840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b46dbcb03e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshots', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
