# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("font: 10pt \"FiraCode Nerd Font\";\n"
"border-color: rgb(255, 101, 30);\n"
"background-color: rgb(85, 85, 127);")
        self.gender_label = QtWidgets.QLabel(Dialog)
        self.gender_label.setGeometry(QtCore.QRect(70, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("FiraCode Nerd Font")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.gender_label.setFont(font)
        self.gender_label.setStyleSheet("font: 14pt \"FiraCode Nerd Font\";")
        self.gender_label.setObjectName("gender_label")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(290, 200, 98, 22))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 200, 98, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(160, 200, 98, 22))
        self.radioButton_3.setStyleSheet("font: 10pt \"FuraCode Nerd Font\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 145, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FiraCode Nerd Font")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 14pt \"FiraCode Nerd Font\";")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 80, 160, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radbtn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("FiraCode Nerd Font")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.radbtn.setFont(font)
        self.radbtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radbtn.setObjectName("radbtn")
        self.verticalLayout.addWidget(self.radbtn)
        self.radbtn2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("FiraCode Nerd Font")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.radbtn2.setFont(font)
        self.radbtn2.setTabletTracking(False)
        self.radbtn2.setObjectName("radbtn2")
        self.verticalLayout.addWidget(self.radbtn2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gender_label.setText(_translate("Dialog", "Gender"))
        self.radioButton.setText(_translate("Dialog", "Fluent"))
        self.radioButton_2.setText(_translate("Dialog", "Beginer"))
        self.radioButton_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic; text-decoration: underline;\">sa</span></p></body></html>"))
        self.radioButton_3.setText(_translate("Dialog", "Intermediate"))
        self.label.setText(_translate("Dialog", "English"))
        self.radbtn.setText(_translate("Dialog", "male"))
        self.radbtn2.setText(_translate("Dialog", "female"))
